#pragma once

enum ErrorCode : unsigned short {
    NONE = 0,

    // Network
    WSA_STARTUP_FAIL = 10,
    WSA_SOCKET_FAIL = 11,
    BIND_FAIL = 12,
    LISTEN_FAIL = 13,
    ACCEPT_FAIL = 14,

    CREATE_IOCP_FAIL = 30,
    CONNECT_IOCP_FAIL = 31,

    WSA_RECV_FAIL = 40,
    WSA_SEND_FAIL = 41,

    FULL_CLIENTS = 50,

    // Application
    CONNECT_REDIS_FAIL = 101,

    USER_ID_DUPLICATED = 211,
    INVALID_CLIENT_INDEX = 222,
    USER_NOT_CONNECTED = 223,
    USER_ALREADY_LOGIN = 224,
    USER_NOT_EXIST = 225,

    ROOM_ENTER_USER_NOT_LOGIN = 270,
    ROOM_ENTER_INVALID_ROOM_INDEX = 273,
    ROOM_ENTER_ROOM_IS_FULL = 276,

    ROOM_LEAVE_USER_NOT_IN_ROOM = 280,
    ROOM_LEAVE_INVALID_ROOM_INDEX = 288,
    ROOM_LEAVE_EMPTY_ROOM = 291,

    ROOM_CHAT_USER_NOT_IN_ROOM = 290,
    ROOM_CHAT_INVALID_ROOM_INDEX = 298
};
